steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}:${TAG_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${TAG_NAME}']

images:
  - '${_IMAGE_NAME}:${TAG_NAME}'

substitutions:
  _IMAGE_NAME: 'us-west1-docker.pkg.dev/urban-nest-2/cloud-run-source-deploy/urbannest-landing'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'projects/urban-nest-2/serviceAccounts/cb-builder@urban-nest-2.iam.gserviceaccount.com'
