steps:
  # Step 1: Build the container image using our Dockerfile
  # We tag it with the unique commit SHA to give it a version
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/urban-nest-landing-page:$SHORT_SHA', '.']

  # Step 2: Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/urban-nest-landing-page:$SHORT_SHA']

  # Step 3: Deploy the specific image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'urban-nest-landing-page' # Your service name
      - '--image=gcr.io/$PROJECT_ID/urban-nest-landing-page:$SHORT_SHA' # The exact image we just built and pushed
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

# This tells Cloud Build what the final image is
images:
  - 'gcr.io/$PROJECT_ID/urban-nest-landing-page:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: projects/$PROJECT_NUMBER/serviceAccounts/$PROJECT_NUMBER@cloudbuild.gserviceaccount.com
