import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: 'Who is Urban Nest for?',
      answer:
        'Urban Nest is designed specifically for real estate professionals, including individual agents, teams, and marketing managers at brokerages who want to create high-quality marketing content faster and more efficiently.',
    },
    {
      question: 'Is the AI content original?',
      answer:
        'Yes, all content generated by Urban Nest is original. Our AI creates unique text and images based on your specific inputs, ensuring your marketing is fresh and tailored to your needs.',
    },
    {
      question: 'Do I need to be tech-savvy to use it?',
      answer:
        'Not at all! Urban Nest features a simple, intuitive interface. If you can write an email, you can use our platform. We designed it to be powerful yet incredibly easy to use, so you can focus on real estate, not software.',
    },
    {
      question: "What if I don't like the generated content?",
      answer:
        'No problem! All our tools include options to refine and regenerate. You can easily tweak your prompts or use our "Enhance with AI" features to guide the AI toward the perfect result.',
    },
  ];

  return (
    <section id="faq" className="py-20 sm:py-28 lg:py-32 bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-text-charcoal">
            Frequently Asked Questions
          </h2>
        </div>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-white rounded-2xl shadow-bold border border-gray-100 overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left"
              >
                <h3 className="text-lg font-bold text-text-charcoal">{faq.question}</h3>
                <ChevronDown
                  className={`w-6 h-6 text-gold transition-transform duration-300 ${
                    openIndex === index ? 'transform rotate-180' : ''
                  }`}
                />
              </button>
              <div
                className={`transition-all duration-300 ease-in-out ${
                  openIndex === index ? 'max-h-96' : 'max-h-0'
                }`}
              >
                <div className="px-6 pb-5">
                  <p className="text-text-charcoal">{faq.answer}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
